### ISSUE TITLE
Short circuiting on error / test failure

### ISSUE THREAD

**Issue by cressie176** [stringtree/hath#4]
Sometimes I want to short circuit a test on error. How would it be if assert returned true when the test failed?

```
if (t.assert(!err, err && err.message)) return done()
```

**Comment by efficacy** [comment]
Hmm. I'm not sure that returning true for a test failure is particularly obvious behaviour.

How about if assert returns true for pass and false for fail? Your example then becomes:

```
if (! t.assert(!err, err && err.message)) return done()
```

but it also allows asserts to be easily composed using regular boolean operations.

**Comment by cressie176** [comment]
I'm good with that
